### PR TITLE
Gen address bug ref #215

### LINKED ISSUE #215: Error generating address
**Describe the bug**
Error in response sequence for `fsm_msgSkycoinAddress` 

**Environment information:**
Any

**Steps to Reproduce**
Run tests for hw-go

**Actual behavior**
Sending a [response by mistake](https://github.com/skycoin/hardware-wallet/blob/160614a3ec458da4e3ca238ecec9f344f54416f9/tiny-firmware/firmware/fsm.c#L393) after a [valid one actually send](https://github.com/skycoin/hardware-wallet/blob/160614a3ec458da4e3ca238ecec9f344f54416f9/tiny-firmware/firmware/fsm.c#L376)

**Expected behavior**
Fix the protocol sequence.
Run integration tests from `go` and `js` libraries after PR.

**Additional context**
This is blocking this https://github.com/skycoin/hardware-wallet-go/pull/121

**Possible implementation**
As `go` library is currently running integration tests from firmware analyze how to avoid fall down in a circular dependency for failing tests.

### PR DESCRIPTION
**Pull request by stdevAlDen**
Fixes #215 

Changes:
- Fxi bug in address gen
- Run hardware-wallet-go integrations tests against emulator.

Does this change need to mentioned in CHANGELOG.md?
no

Requires changes in protobuf specs?
no

Requires testing
no

Comments about testing , should you have some

### CODE REVIEW

File: tiny-firmware/firmware/fsm.c [hunk 1]
```diff
@@ -374,7 +374,9 @@ void fsm_msgSkycoinAddress(SkycoinAddress* msg)
         // fall through
     case ErrOk:
         msg_write(MessageType_MessageType_ResponseSkycoinAddress, resp);
-        break;
+        // NOTE: this return is important to avoid calling
+        // fsm_sendResponseFromErrCode by mistake
```
Comment (olemis) [inline tiny-firmware/firmware/fsm.c]: missing caal to `layoutHome()`
