### PR TITLE
fixes #79 - create long transactions

### LINKED ISSUE #79: Allow to create transactions with more than 8 inputs and 8 outputs
**Feature description**
At this time, if the function to create transactions added in https://github.com/skycoin/hardware-wallet/pull/62 is called with more than 8 inputs or 8 outputs, it fails with `Error: array overflow` (at least when being called from the JS library). It would be good if the function allow many more inputs/outputs.

### PR DESCRIPTION
**Pull request by stdevAdrianPaez**
Fixes #79 

 Changes:	
- Stream inputs and outputs for transactions with more than 8 inputs and/or 8 outputs

Message sequence :

1. Add an optional completion flag , semantics explained below
1. Completion flag not set for transactions with less than 8 inputs and 8 outputs. This case will be handled exactly same as before applying the changes.
1. Split all inputs into chunks of 8 items max.
1. If the number of inputs is over 8 then messages for all chunks will only contain inputs (i.e. empty outputs). Completion flag set to `false`
1. Split outputs into chunks of 8 items max.
1. The message containing the last inputs chunk is allowed to include the first outputs . Completion flag set to `true` if number of outputs is less than 8 .
1. If the number of outputs is over 8 then messages for other chunks will only contain outputs (i.e. empty inputs). The last chunk with outputs should set completion flag to `true`. Up to this point the wallet will compute inner hash internally
1. Resend (all) inputs (since transactions signed by hardware wallet in full). This is necessary due to the combination of two facts. On the one hand [inputs preceding outputs for inner hash](https://github.com/skycoin/skycoin/blob/develop/src/coin/transactions.go#L470-L476) . On the other hand , properties of crypto hashing functions do not allow for obtaining buffer hash from partial hashing values.
1. Handlers for `TxnSignRequest`, `TxnSignAck` , `TxnSignStart` messages .

Any mismatch with respect to the above reported back as failure .

Documentation pull request: https://github.com/skycoin/docs/pull/124

 Does this change need to mentioned in CHANGELOG.md?	
yes

 Requires testing	
yes

 Comments about testing , should you have some

Change submodule protob to other branch, need change to Skycoin repository when https://github.com/skycoin/hardware-wallet-protob/pull/60 merges

### CODE REVIEW

File: skycoin-api/skycoin_crypto.c [hunk 1]
```diff
@@ -436,3 +436,75 @@ void transaction_msgToSign(Transaction* self, uint8_t index, uint8_t* msg_digest
     sha256_Update(&sha256ctx, shaInput, 64);
     sha256_Final(&sha256ctx, msg_digest);
 }
+
+BigTxContext* context;
```
Comment (olemis) [inline skycoin-api/skycoin_crypto.c]: `TxSignContext`

File: skycoin-api/skycoin_crypto.c [hunk 2]
```diff
@@ -436,3 +436,75 @@ void transaction_msgToSign(Transaction* self, uint8_t index, uint8_t* msg_digest
...
+
+BigTxContext* initBigTxContext() {
+    context = malloc(sizeof(BigTxContext));
```
Comment (olemis) [inline skycoin-api/skycoin_crypto.c]: no dynamic allocation

File: skycoin-api/skycoin_crypto.c [hunk 3]
```diff
@@ -436,3 +436,75 @@ void transaction_msgToSign(Transaction* self, uint8_t index, uint8_t* msg_digest
...
+}
+
+void bigTxCtx_printInnerHash(BigTxContext* self) {
+    for(uint8_t i = 0; i < 32; ++i) {
+        printf("%u ", self->innerHash[i]);
+    }
+    printf("\n");
+}
+
+void bigTxCtx_AddHead(uint8_t count) {
```
Comment (olemis) [inline skycoin-api/skycoin_crypto.c]: Head => SizePrefix

File: skycoin-api/skycoin_crypto.c [hunk 4]
```diff
@@ -436,3 +436,75 @@ void transaction_msgToSign(Transaction* self, uint8_t index, uint8_t* msg_digest
...
+    }
+}
+
+void bigTxCtx_finishInnerHash(BigTxContext* self){
+    sha256_Final(&self->sha256_ctx, self->innerHash);
+    self->has_innerHash = true;
+}
+
+void bigTxCtx_Destroy(){
+    free(context);
```
Comment (olemis) [inline skycoin-api/skycoin_crypto.c]: no dynamic memory allocation

File: skycoin-api/skycoin_crypto.c [hunk 5]
```diff
@@ -436,3 +436,75 @@ void transaction_msgToSign(Transaction* self, uint8_t index, uint8_t* msg_digest
...
+    context = NULL;
```
Comment (olemis) [inline skycoin-api/skycoin_crypto.c]: clear all buffers

File: skycoin-api/skycoin_crypto.h [hunk 6]
```diff
@@ -31,6 +32,36 @@ typedef struct Transaction {
     uint8_t innerHash[32];
 } Transaction;
 
+typedef enum _BixTxState {
```
Comment (olemis) [inline skycoin-api/skycoin_crypto.h]: `TxSignState`

File: skycoin-api/skycoin_crypto.h [hunk 7]
```diff
@@ -31,6 +32,36 @@ typedef struct Transaction {
...
+    InnerHashInputs = 0,
+    InnerHashOutputs = 1,
+    Signature = 2,
+} BigTxState;
+
+typedef struct _BigTxOutput{
```
Comment (olemis) [inline skycoin-api/skycoin_crypto.h]: Isn't this defined elsewhere , e.g. [here](https://github.com/skycoin/hardware-wallet/pull/323/files#diff-ed16294f6268df0fb28b30d7e9e214d0R20) . Why duplicate ?

File: skycoin-api/skycoin_crypto.h [hunk 8]
```diff
@@ -50,6 +81,15 @@ void tohex(char* str, const uint8_t* buffer, int buffer_length);
 void tobuff(const char* str, uint8_t* buf, size_t buffer_length);
 void writebuf_fromhexstr(const char* str, uint8_t* buf);
 
+BigTxContext* initBigTxContext(void);
+BigTxContext* getBigTxCtx(void);
+void bigTxCtx_AddHead(uint8_t nbIn);
```
Comment (olemis) [inline skycoin-api/skycoin_crypto.h]: needs docs

**Comment by olemis** [comment]
@stdevAdrianPaez could you please mention here the PR for documenting this feature in the docs ?

File: skycoin-api/skycoin_crypto.c [hunk 9]
```diff
@@ -436,3 +436,73 @@ void transaction_msgToSign(Transaction* self, uint8_t index, uint8_t* msg_digest
...
+    uint8_t* buffer = (uint8_t*)ctx->sha256_ctx.buffer;
+    for(uint8_t i = 0; i < 64; ++i)
+        printf("%u ",buffer[i]);
+    printf("\n");
+}
+
+void TxSignCtx_printInnerHash(TxSignContext* ctx) {
+    char innerHash[64];
+    tohex(innerHash,ctx->innerHash,32);
+    printf("Inner hash: %s\n",innerHash);
```
[the remark this answers is not in the document]
Comment (olemis) [reply skycoin-api/skycoin_crypto.c]: Inner hash is built incrementally as data flows in to the context , so there is an inner hash value at all times . This function is used for testing/debug purpose only .

File: tiny-firmware/firmware/fsm_impl.c [hunk 10]
```diff
@@ -631,3 +640,200 @@ ErrCode_t msgRecoveryDeviceImpl(RecoveryDevice* msg, ErrCode_t (*funcConfirmReco
...
+    }
+    uint8_t inputs[7][32];
+    for (uint8_t i = 0; i < msg->tx.inputs_count; ++i) {
+        writebuf_fromhexstr(msg->tx.inputs[i].hashIn, inputs[i]);
+    }
+    switch (ctx->state) {
+        case InnerHashInputs:
+            if (!msg->tx.inputs_count || msg->tx.outputs_count) {
+                TxSignCtx_Destroy(ctx);
+                return ErrInvalidArg;
```
[the remark this answers is not in the document]
Comment (olemis) [reply tiny-firmware/firmware/fsm_impl.c]: PR description edited accordingly .

File: skycoin-api/skycoin_crypto.h [hunk 11]
```diff
@@ -20,6 +21,7 @@ typedef struct TransactionOutput {
     uint64_t coin;
     uint64_t hour;
     uint8_t address[20];
+    uint32_t address_n[8];
```
[the remark this answers is not in the document]
Comment (RomanMilishchuk) [reply skycoin-api/skycoin_crypto.h]: If it is adding lines not used of code, which sometime in the future could be used then it can be added in the future, when bip32 is added. By now it is reduntant

[the remark this answers is not in the document]
Comment (olemis) [reply skycoin-api/skycoin_crypto.h]: > By now it is redundant

no, the hassle of going through protobuff message update is handled here just once .

[the remark this answers is not in the document]
Comment (RomanMilishchuk) [reply skycoin-api/skycoin_crypto.h]: Even so, could you explain, why do we need BIP-32 for output? It is obvious, that for input we need to know it, so we will sign correctly, but I don't see, how it is connected to the output?

[the remark this answers is not in the document]
Comment (olemis) [reply skycoin-api/skycoin_crypto.h]: > I don't see, how it is connected to the output?

... used (at least) for displaying confirmation screen
