### PR TITLE
Use constants after reviewing #334 for #332

### LINKED ISSUE #332: Changing bootloader even with rdp level 2
**Describe the bug**
As mentioned by trezor [here](https://blog.trezor.io/trezor-one-firmware-update-1-6-1-eecd0534ab95), in STM32F2 chip, there is a way to disable to write protection, so bootloader can be flashed.

**Environment information:**

- OS: any
- Firmware Version: v1 

**Steps to Reproduce**

1. Change in FLASH_OPTCR RDP level from 2 to 0 
2. Load new bootloader using st-link
3. See error

**Actual behavior**
Flash memory controller looks for write-protection in FLASH_OPTCR

**Expected behavior**
Should look for it in OPTION BYTES.

**Additional context**
As it is a problem in ARM chip, there is no way to fix, where the controller is looking for write-protection. 

**Possible implementation**
Precompute hash of bootloader and, when firmware starts running, compute the hash of bootloader, that is on the device and compare to precompiled. If they are different, rewrite the bootloader

### PR DESCRIPTION
**Pull request by olemis**
Fixes #332 

 Changes:	
- Use `SHA_DIGEST_LENGTH` when checking booloader
- Protobuffer submodule points to `develop` branch

Does this change need to mentioned in CHANGELOG.md?	
no

Requires testing	
no

### CODE REVIEW

File: tiny-firmware/firmware/bootloader_integrity.c [hunk 1]
```diff
@@ -10,13 +10,14 @@
  */
 #include "bootloader_integrity.h"
 #include "memory.h"
+#include "sha2.h"
 #include "string.h"
 
 int check_bootloader(void) {
     uint8_t hash[32];
```
Comment (RomanMilishchuk) [inline tiny-firmware/firmware/bootloader_integrity.c]: I think, that here 32 should also be replaced by SHA256_DIGEST_LENGTH.

Comment (RomanMilishchuk) [reply tiny-firmware/firmware/bootloader_integrity.c]: @olemis could you fix that too, so PR could be merged?

Comment (olemis) [reply tiny-firmware/firmware/bootloader_integrity.c]: thanks for the pointer
