### PR TITLE
Fix odebug

### LINKED ISSUE #37: GDB doesn't work on Ubuntu 18.04+
**Describe the bug**
In makefile odebug uses arm-none-eabi-gdb, but it is deprecated and removed from the package manager. For the next versions, we had to use gdb-multiarch.

**Environment information:**

- OS: Linux
- Platform: Ubuntu 18.04+
- Firmware Version: 1.0.0

**Steps to Reproduce**

1. make odebug
2. See error `make: arm-none-eabi-gdb: Command not found`

**Possible implementation**
Add environment parameter $GDB, so everyone can use appropriate debuger.

### PR DESCRIPTION
**Pull request by Macrosrider**
Fixes #37 

 Changes:	
- Added debug with OpenOCD for MacOS and new toolchain support 	

 Does this change need to mentioned in CHANGELOG.md?	
no	

 Requires testing	
no	

 Comments about testing , should you have some

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -202,12 +203,16 @@ st-flash: ## Deploy (flash) firmware on physical wallet
...
-	openocd -f openocd.cfg
+	openocd -f ./debug-scripts/openocd.cfg
 
 odebug: full-firmware
 	## Debug works only on Linux at the moment
+ifeq ($(UNAME_S), Linux)
 	gnome-terminal --command="openocd -f interface/stlink-v2.cfg -f target/stm32f2x.cfg"
-	arm-none-eabi-gdb ./tiny-firmware/skyfirmware.elf \
+else
+	open -a Terminal.app ./debug-scripts/osx-debug.sh
```
Comment (Midren) [inline Makefile]: explicitly show with `ifeq`, that it is work only for OSX

File: debug-scripts/osx-debug.sh [hunk 2]
```diff
@@ -0,0 +1,3 @@
+#!/bin/bash
+
+openocd -f interface/stlink-v2.cfg -f target/stm32f2x.cfg
```
Comment (Midren) [inline debug-scripts/osx-debug.sh:3]: Do we actually need a one-line shell script or it could be inlined in Makefile?

**Review by Midren — CHANGES_REQUESTED** [review]

File: debug-scripts/osx-debug.sh (hunk 2 above)
Comment (Macrosrider) [reply debug-scripts/osx-debug.sh:3]: Yes, because this is the only command we need to run in defferent terminal window and there is no different way to do it

**Review by Midren — APPROVED** [review]
