### PR TITLE
Get memprotect level ref #45

### LINKED ISSUE #45: Detect MEMORY_PROTECTION
- [x] Memory protection query command in bootloader mode (should return RDP level)
- [x] Invert Skycoin logo in bootloader mode if in RDP level is under 2

Whenever possible prefer hardware info over `MEMORY_PROTECT` variable .

### LINKED ISSUE #187: Fix info for features response in bootloader mode
**Describe the bug**
A clear and concise description of the problem and bug effects.

**Environment information:**

- OS: e.g. Linux, Windows, Mac OS X
- Platform: the equivalent of `uname -smr` or `uname -smrv` e.g. Darwin 17.4.0 x86_64
- Firmware Version: e.g. 0.5.18

**Steps to Reproduce**

1. Plug the device in bootloader mode.
2. `go run cmd/cli/cli.go features`
3. Look at the response `{"vendor":"bitcointrezor.com","major_version":1,"minor_version":5,"patch_version":0,"bootloader_mode":true,"firmware_present":true}`

**Actual behavior**
Report **bitcointrezor.com** as vendor.

**Expected behavior**
Should report skycoin as vendor.

**Possible implementation**
Just look at the code:
https://github.com/skycoin/hardware-wallet/blob/7aadfda11ba350f2e67f421d3a5845065057b322/tiny-firmware/bootloader/usb.c#L245

Please be careful as the message is hardcoded in binary format, serialized.

### PR DESCRIPTION
**Pull request by stdevAlDen**
Fixes #45
closes #187 

Changes:
- ask the device for the `RDP` level: `rdp_level`
- `send_msg_features` have a new field ("rdp level info") and changes bitcointrezor.com to skycoin.net
- invert logo if red level is different to `2`.

Does this change need to mentioned in CHANGELOG.md?
yes

Requires changes in protobuff specs?
yes
https://github.com/skycoin/hardware-wallet-protob/pull/49
in bootloader too, in this delta

Requires testing
yes, I need someone to help me to test this feature in a physical device but putting rdp level to 2 will **make the device unable to be flash again**, so be careful

### CODE REVIEW

File: tiny-firmware/bootloader/usb.c [hunk 1]
```diff
@@ -223,55 +223,53 @@ static void send_msg_failure(usbd_device *dev)
...
-	//           - vendor = "bitcointrezor.com"
+	// response: Features message (id 17), payload len 39
+	//           - vendor = "skycoin.net"
 	//           - major_version = VERSION_MAJOR
 	//           - minor_version = VERSION_MINOR
 	//           - patch_version = VERSION_PATCH
 	//           - bootloader_mode = True
 	//           - firmware_present = True/False
 	//           - model = "1"
-	if (brand_new_firmware) {
```
Comment (olemis) [inline tiny-firmware/bootloader/usb.c]: why `brand_new_firmware` not used ?

Comment (stdevAlDen) [reply tiny-firmware/bootloader/usb.c]: @olemis Look at where this value come from, I replaced [this](https://github.com/skycoin/hardware-wallet/blob/8350dbccdd2fdee828996978035c28f39cfccabd/tiny-firmware/bootloader/usb.c#L236-L274) with [this](https://github.com/simelo/skycoin-hardware-wallet/blob/85ab5ec97eac027aa603afaaab7afd075f3a06ce/tiny-firmware/bootloader/usb.c#L238-L254) and conditionally set the value [here](https://github.com/simelo/skycoin-hardware-wallet/blob/85ab5ec97eac027aa603afaaab7afd075f3a06ce/tiny-firmware/bootloader/usb.c#L268-L271).
