### PR TITLE
Random address from random input checking message signature ref #96

### LINKED ISSUE #96: Random address from random input checking message signature
**Describe the bug**
Signature validation is not compliant to the Skycoin API reference implementation.

**Environment information:**

- OS: reproduced on `osx` and `linux`
- Platform: Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
- Firmware Version: 

**Steps to Reproduce**
Once development setup is complted for `skycoin/hardware-wallet` and `skycoin/hardware-wallet-go`

1. Plug the device in USB port
1. Ensure mnemonic is set (no need for pin though)
1. Change working directory to the root of go library repository
1. Execute the following command

```sh
$ go run cli.go deviceCheckMessageSignature --message "aa" --signature "dfd" --address "dfd"
```

**Actual behavior**

The output of the previous command looks like

```
2019/02/07 15:06:30 Success 2! address that issued the signature is: 
"z9J8Z9EyrDoKez7cysWDPJNewLnyUYBgMv
```

**Expected behavior**
Device should complain . Invalid arguments .

### PR DESCRIPTION
**Pull request by stdevAlDen**
Fixes #96

Changes:
- `msgSkycoinCheckMessageSignature` can return success or failed.
- Add test for `SkycoinCheckMessageSignature`.
- check the result of `recover_pubkey_from_signed_message`.
- `msgSkycoinCheckMessageSignatureImpl` can return an error code.

Does this change need to mentioned in CHANGELOG.md?
no

Requires testing
yes

Comments about testing , should you have some

### CODE REVIEW

**Comment by olemis** [comment]
> Error message looks like wrong ?

Nevermind , known issue with hw-go library .

**Comment by stdevAlDen** [comment]
> > Error message looks like wrong ?
> 
> Nevermind , known issue with hw-go library .

@olemis 
Assuming this is correct(firmware), you can not test with hw-go since it(hw-go) lacks this functionality/fix https://github.com/skycoin/hardware-wallet-go/issues/51

trying it under stdevAlDen_t51_check_message_signature_response may works, but maybe I was not finished this yet

File: tiny-firmware/firmware/fsm_impl.c [hunk 1]
```diff
@@ -196,35 +196,47 @@ ErrCode_t msgSkycoinAddress(SkycoinAddress* msg, ResponseSkycoinAddress *resp)
...
+			layoutRawMessage("Wrong signature");
+			ret = ErrFailed;
+		} else {
+			layoutRawMessage("Verification success");
+			memcpy(resp->message, pubkeybase58, pubkeybase58_size);
+		}
 	} else {
-		layoutRawMessage("Wrong signature");
+		strncpy(resp->message,
+				_("Unable to get pub key from signed message"),
```
Comment (olemis) [inline tiny-firmware/firmware/fsm_impl.c]: After fixing skycoin/hardware-wallet-go#51 the feature seems to be working as expected 

```
$ go run cmd/cli/cli.go checkMessageSignature --deviceType EMULATOR --message "aa" --signature "dfd" --address "dfd"
o get pub key from signed message
```

Nevertheless the error message is clipped . This might be related to some issue in protobuffer specs .
@stdevAlDen pls check and create a new issue that's the case

Comment (stdevAlDen) [reply tiny-firmware/firmware/fsm_impl.c]: @olemis firmware bug, hw-go was trying to decode a Failure msg from a Success msg, fixed here:
https://github.com/simelo/skycoin-hardware-wallet/commit/27f77a6455806b165a4dc2a66fa001d58d95952a
