### PR TITLE
fixes #287 #288 - Salt random values used for ECDSA nonces

### LINKED ISSUE #287: Entropy pool is not used for nonces
**Describe the bug**

The entropy pool is not used for nonces.  Nonces are generated with the `random32()` function.  This function is not using entropy from the entropy pool.

### LINKED ISSUE #288: Review entropy.c and use of entropy
**Feature description**

- Review entropy.c for correctness
- Review the use of random numbers in the codebase, ensuring that the entropy is actually used

### PR DESCRIPTION
**Pull request by olemis**
Fixes #287
Fixes #288 

Changes:	
- Set RNG to `random_salted_buffer` during firmware compilation

Does this change need to mentioned in CHANGELOG.md?	
no

Requires testing	
no	

Observations

Bootloader size might change .

### CODE REVIEW

File: tiny-firmware/firmware/entropy.c [hunk 1]
```diff
@@ -195,6 +195,13 @@ void __attribute__((weak)) random_salted_buffer(uint8_t* buf, size_t len)
     bptr = tptr = NULL;
 }
 
+uint32_t __attribute__((weak)) random32_salted(void)
```
Comment (gz-c) [inline tiny-firmware/firmware/entropy.c]: - What does `__attribute__((weak))` mean?

**Comment by olemis** [comment]
> Why do we change the function name, instead of changing the function body?

Because no file in `./tiny_firmware/...` is available for compiling `./skycoin-api/...` . Shall we move `entropy.{c,h}` on to `./skycoin-api` then ?

**Comment by gz-c** [comment]
I mean, why are we replacing `random32()` with `RAND_FUNC` in the source?

I would think that the conditional compilation would control the body of the `random32()` method, not the function name

**Comment by olemis** [comment]
> I mean, why are we replacing `random32()` with `RAND_FUNC` in the source?

Same answer ... I guess . This approach is like a function pointer , but actually resolved at compiled time (i.e. no way to change at run-time). Entropy pool is implemented in `./tiny-firmware`. Firmware salts random values using data read from device hardware sensors and state .

File: tiny-firmware/firmware/entropy.c (hunk 1 above)
Comment (olemis) [reply tiny-firmware/firmware/entropy.c]: >     * What does `__attribute__((weak))` mean?

[weak functions attributes](https://www.valvers.com/programming/c/gcc-weak-function-attributes/)

Comment (olemis) [reply tiny-firmware/firmware/entropy.c]: it's kind of similar to the `RAND_FUNC` symbol I introduced in the patch

File: skycoin-api/tools/ecdsa.c [hunk 2]
```diff
@@ -198,10 +198,11 @@ static void generate_k_random(bignum256* k, const bignum256* prime)
 {
     do {
         int i;
+        random_salted_buffer((uint8_t *) &k->val, sizeof(k->val));
```
Comment (gz-c) [inline skycoin-api/tools/ecdsa.c]: "this generate_k_random function should be completely unchanged, yet use the salted entropy,
i will not accept any code that does otherwise"

Comment (olemis) [reply skycoin-api/tools/ecdsa.c]: Two functions are needed:

- `random32()` is the base (system?) RNG , 32-bits returned
- `random_buffer()` invokes `random32()` in a loop and populates a buffer

on the other hand 

- `random32_salted()` invokes `random_32()` and passes value through the entropy pool, in the process only the first 4 bytes are returned , and 
- `random_salted_buffer()

I am adding a bit more of context based on. a previous private conversation

```
Olemis Lang, [Jun 25, 2019 at 2:35:42 AM]:
I have a question ...

Entropy mixing code deals internally with a 256-bits buffer

Olemis Lang, [Jun 25, 2019 at 2:38:42 AM]:

   196 // generate random K for signing/side-channel noise
   197 static void generate_k_random(bignum256* k, const bignum256* prime)
   198 {
   199     do {
   200         int i;
+  201         RAND_FUNC((uint8_t *) &k->val, sizeof(k->val));
   202         for (i = 0; i < 8; i++) {
!  203             k->val[i] &= 0x3FFFFFFF;
   204         }
!  205         k->val[8] &= 0xFFFF;
   206         // check that k is in range and not zero.
   207     } while (bn_is_zero(k) || !bn_is_less(k, prime));
   208 }

... and there are 9 calls to random32 in here 👆

which of the following 2 alternatives is the right way to salt the random values ?

- mix with entropy pool to obtain a random buffer of, say, 9 * 32 bits = 288 bits and use consecutive 32-bit random values

- salt random values with entropy pool then get first 32 bits , discard the rest , then do that again 8 more times

Olemis Lang, [Jun 25, 2019 at 3:06:38 AM]:
there is another issue ... afaics 

random32() function used in skycoin-api does not seem to use device TRNG

it seems ...

Olemis Lang, [Jun 25, 2019 at 3:11:19 AM]:
> - mix with entropy pool to obtain a random buffer of, say, 9 * 32 bits = 288 bits and use consecutive 32-bit random values

if this 👆 is the way to go ...

Olemis Lang, [Jun 25, 2019 at 3:12:33 AM]:
   196 // generate random K for signing/side-channel noise
   197 static void generate_k_random(bignum256* k, const bignum256* prime)
   198 {
   199     do {
   200         int i;
+  201         RAND_FUNC((uint8_t *) &k->val, sizeof(k->val));
   202         for (i = 0; i < 8; i++) {
!  203             k->val[i] &= 0x3FFFFFFF;
   204         }
!  205         k->val[8] &= 0xFFFF;
   206         // check that k is in range and not zero.
   207     } while (bn_is_zero(k) || !bn_is_less(k, prime));
   208 }

... then this version 👆 should be (at least) close to the final solutión

Steve [sky dev], [Jun 25, 2019 at 4:39:24 AM]:
you can stream 8*32bits
```

jftr

Comment (olemis) [reply skycoin-api/tools/ecdsa.c]: > Olemis Lang, [Jun 25, 2019 at 3:06:38 AM]:
> there is another issue ... afaics 
> 
> random32() function used in skycoin-api does not seem to use device TRNG
> 
> it seems ...

Forget about this . This is linked correctly .

File: skycoin-api/tools/entropypool.c [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+    memset(val1, 0, sizeof(val1));
+    memcpy(entropy_mixer_prev_val, val3, sizeof(entropy_mixer_prev_val));
+    memset(val3, 0, sizeof(val1));
+    if (out_mixed_entropy != NULL) {
+        memcpy(out_mixed_entropy, val2, SHA256_DIGEST_LENGTH);
+    }
+    memset(val2, 0, sizeof(val1));
+}
+
+void entropy_mix_n(const uint8_t* in, size_t in_len, uint8_t* out_mixed_entropy)
```
Comment (gz-c) [inline skycoin-api/tools/entropypool.c]: You can delete this function as its not used. Not worth the complexity

File: skycoin-api/tools/entropypool.c [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+{
+    _random_buffer(buf, len);
+
+    uint8_t tmp[SHA256_DIGEST_LENGTH] = {0};
+    uint8_t *bptr, *tptr;
+    size_t i, j;
+    for (i = len, bptr = buf; i >= SHA256_DIGEST_LENGTH; i -= SHA256_DIGEST_LENGTH) {
+        entropy_mix_256(bptr, SHA256_DIGEST_LENGTH, tmp);
+        for (j = SHA256_DIGEST_LENGTH, tptr = tmp; j; --j, ++tptr, ++bptr) {
+            // FIXME: XOR the whole architecture-specific word
```
Comment (gz-c) [inline skycoin-api/tools/entropypool.c]: Should this be fixed?

File: skycoin-api/tools/entropypool.c [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+
+void random_salted_buffer(uint8_t* buf, size_t len)
+{
+    _random_buffer(buf, len);
+
+    uint8_t tmp[SHA256_DIGEST_LENGTH] = {0};
+    uint8_t *bptr, *tptr;
+    size_t i, j;
+    for (i = len, bptr = buf; i >= SHA256_DIGEST_LENGTH; i -= SHA256_DIGEST_LENGTH) {
+        entropy_mix_256(bptr, SHA256_DIGEST_LENGTH, tmp);
```
Comment (gz-c) [inline skycoin-api/tools/entropypool.c]: `bptr` is a pointer to `buf` which has length `len`.  So using `SHA256_DIGEST_LENGTH` here will overflow `buf` if `len < SHA256_DIGEST_LENGTH`

File: skycoin-api/tools/rand.c [hunk 6]
```diff
@@ -59,23 +66,35 @@ uint32_t random32(void)
...
+    for (; remaining >= 4; ++ptr, remaining -= 4) {
+        *ptr = _random32();
+    }
+    if (remaining > 0) {
+        uint32_t r = _random32();
+        memcpy((void *) ptr, (void *) &r, remaining);
+    }
 }
 
-void __attribute__((weak)) random_buffer(uint8_t* buf, size_t len)
```
Comment (gz-c) [inline skycoin-api/tools/rand.c]: Why was this function rewritten?

File: skycoin-api/tools/entropypool.c (hunk 4 above)
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: the comment is for XOR-ing 32 bits values (STM32 machine word) instead of individual bytes . Might be slightly faster but overcomplicates code . Let's get that done for v2 .

File: skycoin-api/tools/rand.c (hunk 6 above)
Comment (olemis) [reply skycoin-api/tools/rand.c]: because it is meant to mix values with entropy accumulated in the pool .

Comment (olemis) [reply skycoin-api/tools/rand.c]: random buffer not mixed with entropy is returned by `_random_buffer()` .

**Comment by gz-c** [comment]
I'm concerned that random32()'s mixing properties could be bad since the initial buffer length is only 4 bytes. Can you change it so that only 32 byte blocks of TRNG data are mixed at a time?

**Comment by olemis** [comment]
> Can you change it so that only 32 byte blocks of TRNG data are mixed at a time, and use a sliding window to release 32 bits per random32 call?

ok

File: skycoin-api/tools/entropypool.c (hunk 3 above)
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: done

File: skycoin-api/tools/entropypool.c [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+static uint8_t random_buffer_index = 0xff;
+
+_Static_assert(sizeof(random_buffer_cache) % sizeof(uint32_t) == 0, "Alignment error random_buffer_cache");
+
+void random_salted_buffer(uint8_t* buf, size_t len)
+{
+    // Invalidate random32() buffer cache
+    random_buffer_index = 0xff;
+
+    _random_buffer(buf, len);
```
Comment (gz-c) [inline skycoin-api/tools/entropypool.c]: As discussed, `len` must be a multiple of SHA256_DIGEST_LENGTH

File: skycoin-api/tools/entropypool.c [hunk 8]
```diff
@@ -0,0 +1,94 @@
...
+    memcpy(entropy_mixer_prev_val, val3, sizeof(entropy_mixer_prev_val));
+    memset(val3, 0, sizeof(val1));
+    if (out_mixed_entropy != NULL) {
+        memcpy(out_mixed_entropy, val2, SHA256_DIGEST_LENGTH);
+    }
+    memset(val2, 0, sizeof(val1));
+}
+
+// Repeated invocation of `random32_salted` will be resolved from cache
+static uint8_t random_buffer_cache[SHA256_DIGEST_LENGTH] = {0};
```
Comment (Retsediv) [inline skycoin-api/tools/entropypool.c]: looks like you are not updating it anywhere

File: skycoin-api/tools/entropypool.c [hunk 9]
```diff
@@ -0,0 +1,94 @@
...
+#define INTERNAL_ENTROPY_SIZE SHA256_DIGEST_LENGTH
+
+// Accumulated entropy pool
+static uint8_t entropy_mixer_prev_val[SHA256_DIGEST_LENGTH] = {0};
+
+void backup_entropy_pool(uint8_t* buf){
+  memcpy((void *) buf, (void *) entropy_mixer_prev_val, sizeof(entropy_mixer_prev_val));
+}
+
+void entropy_mix_256(const uint8_t* in, size_t in_len, uint8_t* out_mixed_entropy)
```
[the remark this answers is not in the document]
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: what for ? there is a meaning for setting `out_mixed_entropy` to `NULL` which is do not copy to output buffer (performance optimization) , but `in` must be set .

File: skycoin-api/tools/entropypool.c [hunk 10]
```diff
@@ -0,0 +1,94 @@
...
+        val2);
+    uint8_t val3[SHA256_DIGEST_LENGTH] = {0};
+    sha256sum_two(val1, sizeof(val1), val2, sizeof(val2), val3);
+    memset(val1, 0, sizeof(val1));
+    memcpy(entropy_mixer_prev_val, val3, sizeof(entropy_mixer_prev_val));
+    memset(val3, 0, sizeof(val1));
+    if (out_mixed_entropy != NULL) {
+        memcpy(out_mixed_entropy, val2, SHA256_DIGEST_LENGTH);
+    }
+    memset(val2, 0, sizeof(val1));
```
[the remark this answers is not in the document]
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: Good catch . Thnx

File: skycoin-api/tools/entropypool.c (hunk 8 above)
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: yes , it is , see [below](https://github.com/skycoin/hardware-wallet/pull/292/files#diff-6759313892a44f17efc2dfe2a893a5f5R83) ...

File: skycoin-api/tools/rand.c [hunk 11]
```diff
@@ -32,7 +38,8 @@
 #include <assert.h>
 #endif
 
-uint32_t random32(void)
+// This function is not compiled in firmware
+uint32_t __attribute__((weak)) _random32(void)
```
[the remark this answers is not in the document]
Comment (olemis) [reply skycoin-api/tools/rand.c]: the only weak symbols needed are `_random32` and `_random_buffer` .

File: skycoin-api/tools/entropypool.c (hunk 7 above)
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: @gz-c this is the size of random buffer needed by an application . Shouldn't this be considered to be arbitrary ?

Comment (olemis) [reply skycoin-api/tools/entropypool.c]: this is the equivalent to Skycoin's [RandBytes() function](https://github.com/skycoin/skycoin/blob/master/src/cipher/secp256k1-go/secp256_rand.go#L133-L151).

Comment (olemis) [reply skycoin-api/tools/entropypool.c]: I'll apply the changes though

File: skycoin-api/tools/rand.c [hunk 12]
```diff
@@ -59,23 +66,35 @@ uint32_t random32(void)
 // The following code is platform independent
```
[the remark this answers is not in the document]
Comment (olemis) [reply skycoin-api/tools/rand.c]: Not sure , but not related to the issue . This code does not get into firmware . Feel free to create a separate issue to schedule accordingly .

File: skycoin-api/tools/entropypool.c (hunk 7 above)
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: Now I notice , buffer supplied in to this function is allocated by the caller. Hence it is supposed to be of arbitrary size . For the general case [call to entropy_mix_256() below](https://github.com/skycoin/hardware-wallet/pull/292/files#diff-6759313892a44f17efc2dfe2a893a5f5R66) deals with padding . For the `random32()` specific case the buffer used is [rand_buffer_index of size `SHA256_DIGEST_LENGTH`](https://github.com/skycoin/hardware-wallet/pull/292/files#diff-6759313892a44f17efc2dfe2a893a5f5R50).

File: skycoin-api/tools/entropypool.c (hunk 8 above)
Comment (Retsediv) [reply skycoin-api/tools/entropypool.c]: okay, so in `random32_salted` you call the function `random_salted_buffer` where you put as argument `random_buffer_cache` (from my investigation it's the only case when we can change `random_buffer_cache` ([here](https://github.com/skycoin/hardware-wallet/pull/292/files#diff-6759313892a44f17efc2dfe2a893a5f5R87) )

then you call `_random_buffer` ([here](https://github.com/skycoin/hardware-wallet/pull/292/files#diff-6759313892a44f17efc2dfe2a893a5f5R60)), where you just use system implementation of "random number generator" (function `_random32`)

maybe I'm wrong in some point but looks like `random32()` is based on `random_buffer_cache`, which is good. However, `random_buffer_cache` is not related to any salt at all

so, it which step the `system32()` uses salt for random number generation? could you briefly describe this process/workflow?

File: skycoin-api/tools/rand.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (olemis) [reply skycoin-api/tools/rand.c]: > by using conditional compilation, we will have just one random number generator function and then developers can use this function and do not care if it would be used on emulator or real device.

wrong approach

File: skycoin-api/tools/entropypool.c (hunk 8 above)
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: > okay, so in `random32_salted` you call the function `random_salted_buffer` where you put as argument `random_buffer_cache` (from my investigation it's the only case when we can change `random_buffer_cache` ([here](https://github.com/skycoin/hardware-wallet/pull/292/files#diff-6759313892a44f17efc2dfe2a893a5f5R87) )

`random_salted_buffer` is the translation of Skycoin's [func RandByte(n int) []byte](https://github.com/skycoin/skycoin/blob/master/src/cipher/secp256k1-go/secp256_rand.go#L133-L151) . @Retsediv do you notice any difference ?

Comment (olemis) [reply skycoin-api/tools/entropypool.c]: > looks like `random32()` is based on `random_buffer_cache`

`random32()` is based on `random_salted_buffer` so as to avoid using padding

Comment (olemis) [reply skycoin-api/tools/entropypool.c]: >  could you briefly describe this process/workflow?

Based on Skycoin's

```
$ grep -nr Mix256 src/
src//cipher/secp256k1-go/secp256_rand.go:51:// Mix256 mixes in 256 bits, outputs 256 bits
src//cipher/secp256k1-go/secp256_rand.go:52:func (ep *EntropyPool) Mix256(in []byte) (out []byte) {
src//cipher/secp256k1-go/secp256_rand.go:79:		tmp := ep.Mix256(buff[32*i : 32+32*i]) //32 byte slice
src//cipher/secp256k1-go/secp256_rand.go:127:	_ent.Mix256(seed1)
src//cipher/secp256k1-go/secp256_rand.go:128:	_ent.Mix256(seed2)
src//cipher/secp256k1-go/secp256_rand.go:129:	_ent.Mix256(seed3)
src//cipher/secp256k1-go/secp256_rand.go:130:	_ent.Mix256(seed4)
```

File: skycoin-api/tools/entropypool.c (hunk 10 above)
[the remark this answers is not in the document]
Comment (gz-c) [reply skycoin-api/tools/entropypool.c]: Still not fixed

File: skycoin-api/tools/entropypool.c [hunk 13]
```diff
@@ -0,0 +1,94 @@
...
+    uint8_t val2[SHA256_DIGEST_LENGTH] = {0};
+    sha256sum_two(
+        val1, sizeof(val1),
+        entropy_mixer_prev_val, sizeof(entropy_mixer_prev_val),
+        val2);
+    uint8_t val3[SHA256_DIGEST_LENGTH] = {0};
+    sha256sum_two(val1, sizeof(val1), val2, sizeof(val2), val3);
+    memset(val1, 0, sizeof(val1));
+    memcpy(entropy_mixer_prev_val, val3, sizeof(entropy_mixer_prev_val));
+    memset(val3, 0, sizeof(val1));
```
Comment (gz-c) [inline skycoin-api/tools/entropypool.c]: sizeof(val3)

File: skycoin-api/tools/entropypool.c (hunk 7 above)
Comment (gz-c) [reply skycoin-api/tools/entropypool.c]: I'll repeat: it is incorrect to use a buffer length that is not a multiple of SHA256_DIGEST_LENGTH at this point in the mechanism. This code is incorrect, since it allows a an arbitrary length to be used.

File: skycoin-api/tools/entropypool.c (hunk 8 above)
Comment (Retsediv) [reply skycoin-api/tools/entropypool.c]: > `random32()` is based on `random_salted_buffer` so as to avoid using padding

But how does it depend on any kind of salt? Could you, please, show me the specific pieces of code? My point is that I do not see where do you use salt for `random32()`

File: skycoin-api/tools/rand.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (Retsediv) [reply skycoin-api/tools/rand.c]: > > by using conditional compilation, we will have just one random number generator function and then developers can use this function and do not care if it would be used on emulator or real device.
> 
> wrong approach

why?

File: skycoin-api/tools/entropypool.c (hunk 8 above)
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: see `tiny_firmware/firmware/entropy.c`

File: skycoin-api/tools/entropypool.c (hunk 13 above)
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: sorry , had those changes applied in my local working copy , forgot to push ...

Comment (olemis) [reply skycoin-api/tools/entropypool.c]: fixed now

File: skycoin-api/tools/entropypool.c (hunk 7 above)
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: > it is incorrect to use a buffer length that is not a multiple of SHA256_DIGEST_LENGTH at this point in the mechanism.

then I see 2 options to get this done :

- Change return value to be of type `size_t` then try to fill the buffer up to the closest multiple of `SHA256_DIGEST_LENGTH` and return the number of random bytes actually generated
- Change return value to be of type `size_t` then return `0` if `len` is not multiple of `SHA256_DIGEST_LENGTH` or `len` otherwise .

which one is the right choice ?

File: skycoin-api/tools/entropypool.c (hunk 10 above)
[the remark this answers is not in the document]
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: done

File: skycoin-api/tools/entropypool.c (hunk 7 above)
Comment (olemis) [reply skycoin-api/tools/entropypool.c]: >     * Keep things as they are , round by excess to next multiple of `SHA256_DIGEST_LENGTH` and discard bytes that do not fit in `len`

I'd choose this option . Is that ok ?

Comment (olemis) [reply skycoin-api/tools/entropypool.c]: > I'll repeat: it is incorrect to use a buffer length that is not a multiple of SHA256_DIGEST_LENGTH at this point in the mechanism.

Considering the `SHA256_DIGEST_LENGTH` is set to `32` bytes , what shall be done in the case of [pin code matrix requesting 9 random bytes](https://github.com/skycoin/hardware-wallet/blob/develop/tiny-firmware/firmware/pinmatrix.c#L64) (see [random_permute](https://github.com/skycoin/hardware-wallet/blob/develop/skycoin-api/tools/rand.c#L81-L89) and [random_uniform](https://github.com/skycoin/hardware-wallet/blob/develop/skycoin-api/tools/rand.c#L62-L68) ).

Comment (olemis) [reply skycoin-api/tools/entropypool.c]: > what shall be done in the case of [pin code matrix requesting 9 random bytes](https://github.com/skycoin/hardware-wallet/blob/develop/tiny-firmware/firmware/pinmatrix.c#L64)

Considering this , neither option 1 nor event 2 are correct ... and since there is an actual need for generating buffers of length smaller than `SHA256_DIGEST_LENGTH` then I see no other alternative but implementing option 3 ...

... unless there is another way to approach this .

File: skycoin-api/tools/rand.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (olemis) [reply skycoin-api/tools/rand.c]: see Trezor

**Comment by YuraYelisieiev** [comment]
> Can a function-scoped static counter be used for that? @YuraYelisieiev 

Sorry, for the late reply. Missed this issue. If it`s still relevant, I think it would be a good idea. As I see in this [PR](https://github.com/skycoin/hardware-wallet/pull/292/files#diff-6759313892a44f17efc2dfe2a893a5f5R79) it`s implemented in another way, but I can understand your proposal in another way.  @gz-c

**Comment by YuraYelisieiev** [comment]
@olemis As I know Asserts are used only during the test period. Will you change it later? Or we will leave them?

**Comment by jdknives** [comment]
@olemis apparently the PR  is still not mergable as @gz-c has reservations about the  code. I would like @RomanMilishchuk to take a shot at it.

File: skycoin-api/tools/entropypool.c [hunk 14]
```diff
@@ -0,0 +1,114 @@
...
+    // Invalidate random32() buffer cache
+    random_buffer_index = 0xff;
+
+    // Random bytes to be mixed with entropy pool have to fit in buckets of size SHA256_DIGEST_LENGTH
+    // to prevent padding added by mixing function.
+
+    // buffer_tail_length happens to be the number of bytes that do not fit in chunks of SHA256_DIGEST_LENGTH
+    size_t buffer_tail_length = len % SHA256_DIGEST_LENGTH;
+    // buffer_tail_length happens to be multiple of SHA256_DIGEST_LENGTH
+    size_t buffer_block_length = len - buffer_tail_length;
```
Comment (gz-c) [inline skycoin-api/tools/entropypool.c]: If `len` is 0 it should pad to `SHA256_DIGEST_LENGTH`

File: skycoin-api/tools/entropypool.c [hunk 15]
```diff
@@ -0,0 +1,114 @@
...
+        }
+        rndptr = NULL;
+    }
+    memset(&tmp, 0, sizeof(tmp));
+    bufptr = tmpptr = NULL;
+}
+
+uint32_t random32_salted(void)
+{
+    // On index overflow regenerate new random buffer
```
Comment (gz-c) [inline skycoin-api/tools/entropypool.c]: Better if the buffer is static local to this function to keep it scoped
